id: I08EDF67B
legacy_id: P009284
ocr_import_info:
  bdrc_scan_id: W3CN7543
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T04:28:44'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T15:41:06.672545+00:00'
last_modified: 2022-09-03 23:41:43.985164
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN7543
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN7543
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཏེར་ཆེན་བདུད་ཀློང་ཟུང་གི་གཏེར་བྱོན་སྨིན་བྱེད་ཐམས་ཅད་ཆུ་འབབས་སུ་བཀོད་པ།
  author: ཀློང་གསལ་སྙིང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.9021579592011939
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I3CN7548:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7548
      total_pages: 563
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I3CN7548.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9154294060835027
    legacy_id: v004
  I3CN7547:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7547
      total_pages: 453
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3CN7547.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8834054112495265
    legacy_id: v003
  I3CN7545:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN7545
      total_pages: 681
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN7545.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9023693260708675
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
