id: I08EDF67B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T04:30:01+00:00'
last_modified: '2022-06-08T09:55:30.085101+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7543
  title: གཏེར་ཆེན་བདུད་ཀློང་ཟུང་གི་གཏེར་བྱོན་སྨིན་བྱེད་ཐམས་ཅད་ཆུ་འབབས་སུ་བཀོད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4BBA:
      image_group_id: I3CN7545
      title: ''
      total_pages: 681
      order: 1
      base_file: 4BBA.txt
    57EB:
      image_group_id: I3CN7546
      title: ''
      total_pages: 0
      order: 2
      base_file: 57EB.txt
    '9434':
      image_group_id: I3CN7547
      title: ''
      total_pages: 453
      order: 3
      base_file: 9434.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
